### ISSUE TITLE
how to define an adaptive height complex cell?

### ISSUE THREAD

**Issue by wupengFEX** [aksonov/react-native-tableview#113]
how to define an adaptive height complex cell?

**Comment by dac09** [comment]
So I've just attempted this today, and the way I achieved it is 
```
<Cell>
<TouchableWithoutFeedback onPress={() => {this.setState({showExtraInfo: !this.state.showExtraInfo)}>
<Text> Example data </Text>
{this.state.showExtraInfo && <Text>Some more info for you</Text>
</TouchableWithoutFeedback>
</Cell>
```

While this will work, I don't think the native bit of this is implemented in quite the most efficient manner, as a result if you try to animate it, you'll get artefacts.

I'm not an expert, but I've been told for more complex UIs, its best to use a ScrollView in iOS (implemented within ListView of react native) instead, which might explain why the author implemented the CellView with reloadData instead of reloadRow.
