### ISSUE TITLE
In iPad (RN 0.14.2) the arrows get far from the right margin and the cell lines don't show from margin to margin

### ISSUE THREAD

**Issue by nbastoWM** [aksonov/react-native-tableview#56]
![image](https://cloud.githubusercontent.com/assets/15138821/11394194/7f9f51be-935b-11e5-97dc-376c445e48f2.png)

**Comment by aksonov** [comment]
This component is just wrapper around built-in UITableView.

**Comment by iosipeld** [comment]
@nbastoWM 

This behaviour is caused by a property introduced in iOS9: cellLayoutMarginsFollowReadableWidth

As a workaround, you can add these lines inside RNTableView.m in createTableView:

```
if([_tableView respondsToSelector:@selector(setCellLayoutMarginsFollowReadableWidth:)]){
    _tableView.cellLayoutMarginsFollowReadableWidth = NO;
}
```

I am going to find a right solution when I have time, but for now it's not destroying a layout so it's OK.
