### ISSUE TITLE
Possible memory leak in RNTableViewCell

### ISSUE THREAD

**Issue by dlahyani** [aksonov/react-native-tableview#77]
The memory leak is caused by a retain cycle between <code>RNTableViewCell</code> and <code>RNCellView</code>.  <code>RNCellView</code> holds its containing <code>RNTableViewCell</code> strongly while <code>RNTableViewCell</code> retains the contained <code>RNCellView</code> strongly by adding it as subview to its <code>contentView</code>.

Suggested solution: <code>RNCellView</code> should not hold its containing <code>RNTableViewCell</code>, at leat it must not do hold it strongly.

**Comment by chetstone** [comment]
Just found this problem in my app, at least I suppose it is the same problem. When switching to a tab with many `<Cell>` items, the number of total views as shown by the RN Perf Monitor increases, and when switching back to the original tab, it does not drop to the original value and in fact increases more. Changing the `<Cell>s` to `<Item>s` shows the expected behaviour of total views returning to the original value when switching back to the original tab.

Of course this causes the total memory consumed by the app to increase each time the view with `<Cell>s` is switched to.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
