### ISSUE TITLE
On android what i can use

### ISSUE THREAD

**Issue by lekenny** [aksonov/react-native-tableview#99]

**Comment by ruaan** [comment]
Solutions  ?

**Comment by lekenny** [comment]
@ruaan   you can look react-native-swipe-list-view

**Comment by wwwdata** [comment]
Is there any similar project for android? I searched and didn't find anything so far. Our use case is to display a huge list of like 2k names that we need to be able to jump to a specific entry. Image the iOS Address book with the A-Z bar at the right side. With the react-native ScrollView, it's only possible to jump to stuff that was already rendered and I cannot jump to the middle of the list for example.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. Right now we have no plans for android. Thanks!

**Comment by leoi11** [comment]
Just FYI, the closest one I can find from npm is this package. https://www.npmjs.com/package/react-native-tableview-simple

It supports both android and iOS, and that comes with a cost (the appearance is completely based on CSS styling rather than using the native components, which means the look and feel don't get updated as the native components change.)
